### ISSUE TITLE
Typo in link to "command compatibility"

### ISSUE THREAD

**Issue by MihanEntalpo** [alisaifee/coredis#10]
In the readme file there is a link "https://coredis.readthedocs.org/en/stable/compatibility" that opens 404 erorr page. It really should be "https://coredis.readthedocs.io/en/stable/compatibility.html".
I thought its such a little fix that it's not worth creating fork of repo, changing readme file, and creating pull request back to your repo.

**Comment by alisaifee** [comment]
Thanks!
