### ISSUE TITLE
Performance of XADD

### ISSUE THREAD

**Issue by dvzubarev** [alisaifee/coredis#112]
Hi, I measured performance for some specific commands that are important for my project.
Namely, multiple `XADD` commands, combined in a pipeline and `XREADGROUP`.
You can see the [code](https://gitlab.com/dvzubarev/py_redis_clients_benchmark/-/blob/master/py_redis_clients_benchmark/common.py#L64) [here](https://gitlab.com/dvzubarev/py_redis_clients_benchmark/-/blob/master/py_redis_clients_benchmark/coredis4_bench.py#L10).
I used native extensions and hiredis whenever possible, redis version was 7.0, python 3.10.
The best one from three runs is picked up.

| run # | lib version              | time (s) |
|-------|--------------------------|----------|
|     1 | coredis-2.3.1            |    1.182 |
|     0 | coredis-3.0.3            |     2.19 |
|     0 | coredis-3.8.5            |    2.287 |
|     2 | coredis-3.5.1            |     2.33 |
|     0 | coredis-2.3.1-wo-hiredis |    2.722 |
|     2 | coredis-3.11.5           |    2.865 |
|     0 | coredis-4.2.1            |    3.029 |
|     1 | coredis-4.0.2            |    3.048 |
|     2 | coredis-4.4.0            |    3.106 |
|     2 | coredis-4.6.0            |    3.135 |
|     2 | coredis-4.6.0-wo-ext     |    4.112 |

I profiled 4.6.0 version and discovered that bottlneck is in `bind_partial` (it calls `_bind`) method.
<details>
  <summary>Sorted by cumtime</summary>

```
# calls      tottime          cumtime
        3    0.406    0.135   45.536   15.179 {method 'run_until_complete' of 'uvloop.loop.Loop' objects}
     1080    0.451    0.000   40.826    0.038 /home/dvzubarev/Workspace/projects/textapp/py_redis_clients_benchmark/py_redis_clients_benchmark/coredis4_bench.py:11(coredis_add_bench)
   640000    0.432    0.000   30.878    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:83(wrapper)
   640000    1.104    0.000   30.446    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/commands/_validators.py:109(wrapped)
   640021    2.388    0.000   16.678    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/commands/_wrappers.py:173(wrapped)
   640008    0.322    0.000   10.906    0.000 /nix/store/9srs642k875z3qdk8glapjycncf2pa51-python3-3.10.7/lib/python3.10/inspect.py:3181(bind_partial)
   640008    7.939    0.000   10.585    0.000 /nix/store/9srs642k875z3qdk8glapjycncf2pa51-python3-3.10.7/lib/python3.10/inspect.py:3043(_bind)
   640021    0.573    0.000    9.786    0.000 /nix/store/9srs642k875z3qdk8glapjycncf2pa51-python3-3.10.7/lib/python3.10/contextlib.py:194(__aenter__)
  1280030    0.620    0.000    8.430    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/commands/_wrappers.py:78(__call__)
     1688    0.005    0.000    7.896    0.005 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:615(execute)
   640000    2.713    0.000    7.370    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/commands/core.py:5019(xadd)
641317/641312    1.835    0.000    5.481    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/connection.py:530(create_request)
      892    0.668    0.001    4.052    0.005 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:440(_execute_transaction)
     1736    0.999    0.001    3.814    0.002 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/connection.py:314(data_received)
      796    0.534    0.001    3.716    0.005 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:538(_execute_pipeline)
   640000    0.853    0.000    3.588    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:338(execute_command)
   641744    2.333    0.000    2.515    0.000 {method 'get_response' of 'Parser' objects}
   640000    1.030    0.000    1.762    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/commands/_validators.py:112(<setcomp>)
   641302    1.654    0.000    1.654    0.000 {method 'pack_command' of 'Packer' objects}
   640640    1.223    0.000    1.572    0.000 /home/dvzubarev/Workspace/projects/textapp/py_redis_clients_benchmark/py_redis_clients_benchmark/common.py:7(gen_records)
   640000    1.156    0.000    1.506    0.000 /nix/store/dl4sqq10fv8w0zl83m682fi9bkqafc7s-python3.10-coredis-4.6.0/lib/python3.10/site-packages/coredis/pipeline.py:412(pipeline_execute_command)
```

</details>

It seems that this method is called in `mutually_inclusive_parameters` decorator of `xadd` function.
So I replaced `xadd` call with `execute_command` and it significantly sped up newer versions.

| run # | lib version              | time (s) |
|-------|--------------------------|----------|
|     0 | coredis-3.11.5           |   0.8467 |
|     0 | coredis-3.8.5            |    1.046 |
|     0 | coredis-3.5.1            |    1.108 |
|     0 | coredis-4.0.2            |    1.137 |
|     1 | coredis-4.2.1            |    1.158 |
|     0 | coredis-2.3.1            |    1.163 |
|     2 | coredis-4.4.0            |    1.195 |
|     0 | coredis-3.0.3            |    1.307 |
|     1 | coredis-4.6.0            |    1.408 |
|     1 | coredis-4.6.0-wo-ext     |    2.534 |
|     0 | coredis-2.3.1-wo-hiredis |    2.721 |

I hope this information may help you to speed up some parts of this great library, since I saw many commands, which use `mutually_inclusive_parameters` or `mutually_exclusive_parameters` decorators.

**Comment by alisaifee** [comment]
Thanks for the very detailed and comprehensive measurements! I've struggled with figuring out how to remove the overhead caused by the validation decorators (`mutally_{inclusive,exclusive}_parameters`) before and didn't have much success. 

I've been considering adding an "optimized" flag that disables this and a few other validations as a stop gap measure. Would that work for you?

**Comment by dvzubarev** [comment]
> I've been considering adding an "optimized" flag that disables this and a few other validations as a stop gap measure. Would that work for you?

Yes, I think it will work.

**Comment by alisaifee** [comment]
I've pushed a first cut of the [optimized mode](https://coredis.readthedocs.io/en/latest/handbook/optimization.html#optimized-mode) to master if you'd like to try it out.

**Comment by alisaifee** [comment]
I'll release this in 4.7.0 shortly.

**Comment by alisaifee** [comment]
My apologies, I closed this too early and should have waited for you to confirm with your benchmark.

**Comment by dvzubarev** [comment]
No problem, I have tried new version:

| run # | lib version              | time (s) |
|-------|--------------------------|----------|
| 0 | coredis-4.7.0 | 3.572 |
| 1 | coredis-4.7.0 | 3.563 |
| 2 | coredis-4.7.0 | 3.576 |

With `COREDIS_OPTIMIZED`
| run # | lib version              | time (s) |
|-------|--------------------------|----------|
| 0 | coredis-4.7.0 | 2.544 |
| 1 | coredis-4.7.0 |  2.55 |
| 2 | coredis-4.7.0 | 2.546 |

If I want more speed I always can use `execute_command` directly. I think I may close now.
