### ISSUE TITLE
rpop and lpop missing count arg

### ISSUE THREAD

**Issue by dynalz** [alisaifee/coredis#12]
## Checklist

- Python version
- Any

- Using hiredis or just Python parser
- Irrelevant

- Using uvloop or just asyncio event loop
- Irrelevant

- Does issue exists against the `master` branch of aredis?
- Yes

## Steps to reproduce
StrictRedis.lpop("any-key", count=10)

## Expected behavior
Popping 10 elements from "any-key" list

## Actual behavior
TypeError: lpop() got an unexpected keyword argument 'count'

**Comment by dynalz** [comment]
#13

**Comment by dynalz** [comment]
#13 - PR Fix

**Comment by alisaifee** [comment]
You can try using the version on master (or the `3.0.0rc1` release on pypi)

```python
import asyncio
import coredis


async def test_list():
    client = coredis.Redis()
    await client.lpush("list", 1)
    await client.lpush("list", 2)
    await client.lpush("list", 3)

    single = await client.lpop("list")
    popped = await client.lpop("list", count=2)
    print(single, popped)
    # b'3' [b'2', b'1']


asyncio.new_event_loop().run_until_complete(test_list())

```
