### ISSUE TITLE
Command responses don't match command requests

### ISSUE THREAD

**Issue by shananin** [alisaifee/coredis#143]
Hi,
I tried to use this lib on production and got many strange errors

```
await r.publish(topic, val)
...
response from redis 'OK'
exception: Unable to map 'OK' to int
```

```
val = await r.get(self.key())
...
response from redis 1
exception: Unable to map 1 to AnyStr
```

```
await r.publish(topic, val)
...
(in the Sentry stack trace)
await self.create_request(b"HELLO", *hello_command_args, decode=False)
...
exception: only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```

also, I had many `list index out of range` errors.

Any suggestions what it could be and if I can fix it? It looks like responses from other commands.

I used the lib for `set`, `get` and `publish`, `subscribe` commands

```python3
r = await Redis.from_url(
      redis_addr,
      max_connections=10000,
      decode_responses=True,
      protocol_version=2,
)

async def save():
    await r.set('key', 'val', 300)

async def subscribe():
    pubsub = r.pubsub()
    await pubsub.subscribe('topic')
    try:
        while pubsub.subscribed:
            msg = pubsub.get_message(ignore_subscribe_messages=True, timeout=10)
            yield msg
    finally:
        pubsub.close()
```

**Comment by alisaifee** [comment]
This looks pretty interesting/bizarre. Could you share the details of the redis server that you are connecting to?

**Comment by shananin** [comment]
I use aws elasticache redis 5.0.6 cluster mode off. Also, I use Sanic as webserver.
before I used `aioredis` lib and didn't have this issue. 
I think I don't use the pool connections properly. I used context manager for aioredis:
```python3
async with client as conn:
    await conn.set('key', 'val', 300)
```
Does coredis have something similar?

**Comment by alisaifee** [comment]
For the commands you shared in your sample there are some api usage errors.
- `set` only takes two positional arguments (key & value). Everything else should be keyword arguments, I think in your case you want to use `ex=300`? ([reference](https://coredis.readthedocs.io/en/latest/api.html#coredis.Redis.set))
- `PubSub.get_message()` is an async method so you'll need an `await`. ([reference](https://coredis.readthedocs.io/en/latest/api.html#coredis.commands.PubSub.get_message))

**Comment by alisaifee** [comment]
- 5.x should work with RESP2 (which you correctly specified).
- coredis doesn't have a similar concept of an async context manager to explicitly reserve a connection from the pool, every time you issue a command with the `coredis.Redis` client a connection will be reserved for sending the command and released back as soon as possible (in most cases before the response is received so that it can be reused).

**Comment by alisaifee** [comment]
> exception: only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
That error implies that somehow the connection reserved by the pubsub listener ended up getting reused for the `publish` method - which should not be possible but clearly is.

**Comment by shananin** [comment]
thanks for the fast responses. I use Sanic for graphql websockets and I guess the issue is related to incorrect task canceling during websocket closing.
I'll try to update or change the web framework.

**Comment by alisaifee** [comment]
> I use Sanic for graphql websockets and I guess the issue is related to incorrect task canceling during websocket closing.

I'm actually pretty curious how the client got into this state because it looks like there definitely is a bug in the cleanup/connection pool reuse code under certain conditions. Is there some sample code that you have which I could use to reproduce this myself?

**Comment by alisaifee** [comment]
@shananin just curious, was the issue resolved for you? And if so what change did you have to make?
