### ISSUE TITLE
Do retries/reconnections on fails

### ISSUE THREAD

**Issue by roma-glushko** [alisaifee/coredis#150]
Doesn't seem like coredis attempts to do any reconnections or retries when it's failed to access redis instances. In case of cloud environment, it's specifically important as you cannot guarantee that your request will go through from the first try (e.g. network partitions, package loss, etc). 

In case of redis cluster setup, we may have more reasons to retry and reconnect (e.g. one of the nodes may be scheduled and waiting for a new place in the cluster what makes it unconnected from the cluster for bit but other nodes are still there to serve requests).

Having no reconnection logic like that makes connections very unstable requiring some external logic to cover that up.

If it's possible to bring that on, that would be great.

**Comment by alisaifee** [comment]
The cluster client has some level of retrying capability but you're right the standalone client does not. Integrating with something like [aioretry](https://github.com/kaelzhang/python-aioretry) could be an option

**Comment by roma-glushko** [comment]
@alisaifee the funny thing is I'm talking about RedisCluster case 😌  Maybe this is a side effect of https://github.com/alisaifee/coredis/issues/149. That's entirely possible.

In any case, the important piece is that it's about pub/sub. If you do similar redis cluster instance restarts like I have described in https://github.com/alisaifee/coredis/issues/149, then you could end up having your subscriptions fail with ConnectionError exceptions.

> the standalone client does not

Yeah, it would be definitely useful in all setups: standalone redis, sentinel or cluster.

> Integrating with something like [aioretry](https://github.com/kaelzhang/python-aioretry) could be an option

Another option is to have it implemented in-house like in: 
- https://github.com/redis/redis-py/blob/6c708c2e0511364c2c3f21fa1259de05e590632d/redis/asyncio/retry.py - `redis-py`
- https://github.com/roma-glushko/hyx/blob/main/hyx/retry/manager.py - my recent project

**Comment by alisaifee** [comment]
Makes sense. For pubsub there is a completely disconnected retry logic - which only retries on timeout errors. If the issue you are facing is indeed related to the cluster topology changing without the client being made aware then the retry logic is useless since it'll keep retrying against the same (invalid) `host:port`

**Comment by alisaifee** [comment]
@roma-glushko I think the main issue here is #149 so if you feel that the retry requirements are sufficiently addressed as part of the fixes for that - please close this issue.

**Comment by roma-glushko** [comment]
@alisaifee improvements from #149 is definitely going to solve this issue as well! Thank you Ali for improving this experience in such short terms 🙏
