### ISSUE TITLE
type overload for lpop

### ISSUE THREAD

**Issue by Le0Developer** [alisaifee/coredis#175]
Currently `.rpop()` is correctly type overloaded with regards to the `count` argument – `.lpop()` has no overload at all.

https://github.com/alisaifee/coredis/blob/79a19bb797686a29eb8462bf0ece4725efcb3683/coredis/commands/core.py#L3536-L3550

https://github.com/alisaifee/coredis/blob/79a19bb797686a29eb8462bf0ece4725efcb3683/coredis/commands/core.py#L3366-L3372

## Expected Behaviour

`.lpop()` should have similar type overloads.

**Comment by alisaifee** [comment]
Thanks, addressed in 8f54dba9e2bd854aa30a87679807ceffaf9e6b1b and will be available in the next release
