### ISSUE TITLE
TypeError from zpopmin()/zpopmax() with count

### ISSUE THREAD

**Issue by bradnewman** [alisaifee/coredis#221]
## Expected Behaviour

Calling `zpopmin()` or `zpopmax()` with an explicit `count` specified should return a `tuple[ScoredMember, ...]`, with one `ScoredMember` for each item removed from the sorted set.

## Current Behaviour

A `TypeError` is raised from within Coredis.

## Steps to Reproduce

```python
    await client.zadd("myzset", {"1": 1})
    await client.zadd("myzset", {"2": 2})
    result = await client.zpopmin("myzset", count=2)  
```

Full stack trace:
```
.venv/lib/python3.11/site-packages/coredis/commands/_wrappers.py:212: in wrapped
    async with command_cache(callable, *args, **kwargs) as response:
/usr/lib/python3.11/contextlib.py:210: in __aenter__
    return await anext(self.gen)
.venv/lib/python3.11/site-packages/coredis/commands/_wrappers.py:106: in __call__
    yield await func(*args, **kwargs)
.venv/lib/python3.11/site-packages/coredis/commands/core.py:4412: in zpopmin
    return await self.execute_command(
.venv/lib/python3.11/site-packages/coredis/client/cluster.py:763: in execute_command
    return await self.retry_policy.call_with_retries(
.venv/lib/python3.11/site-packages/coredis/retry.py:60: in call_with_retries
    return await func()
.venv/lib/python3.11/site-packages/coredis/client/cluster.py:814: in _execute_command
    return await self._execute_command_on_single_node(
.venv/lib/python3.11/site-packages/coredis/client/cluster.py:940: in _execute_command_on_single_node
    response = callback(
.venv/lib/python3.11/site-packages/coredis/response/_callbacks/__init__.py:92: in __call__
    return self.transform_3(cast(RESP3, response), **options)
.venv/lib/python3.11/site-packages/coredis/response/_callbacks/sorted_set.py:114: in transform_3
    return tuple(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f1bb052b2b0>

    return tuple(
>       ScoredMember(*v) for v in cast(List[Tuple[AnyStr, float]], response)
    )
E   TypeError: ScoredMember.__new__() missing 1 required positional argument: 'score'

.venv/lib/python3.11/site-packages/coredis/response/_callbacks/sorted_set.py:115: TypeError
```

1. Reproduced with both `Redis` and `RedisCluster`; reproduced with various numbers of elements in the sorted set and various values of `count`
2. Omitting `count` (or setting explicitly to `None`) does not encounter this issue
3.  I have also seen a different error from the same line:
    ```
    E   TypeError: ScoredMember.__new__() takes 3 positional arguments but 4 were given
    ```

## Your Environment

- coredis version: 6.1.4
- Redis version: 6.2.1
- Operating system: Ubuntu 22.04 x86_64
- Python version: 3.11.7

**Comment by alisaifee** [comment]
Just some initial notes:
- I wasn't able to reproduce the issue in redis >= `7.0`
- I was able to reproduce it with redis `6.2.0` and only with `protocol_version=3` (i.e. `RESP3`). It is possible that there is a bug with `RESP3` responses for `zpopmin/max` where a flat array instead of a nested array is being returned.

**Comment by alisaifee** [comment]
Interestingly the issue does not exist with redis `6.2.6` (which is what the CI tests against)

**Comment by alisaifee** [comment]
Related: https://github.com/redis/redis/pull/8981

**Comment by bradnewman** [comment]
Thanks - updating to Redis 6.2.6 is a good enough solution for me.

**Comment by alisaifee** [comment]
@bradnewman please close the issue if you feel satisfied with the solution.
