### ISSUE TITLE
Redict/Valkey support?

### ISSUE THREAD

**Issue by coandco** [alisaifee/coredis#226]
Given the recent flap about Redis changing its license to one that doesn't meet the definition of open source software, do you plan to support either of the two major forks of Redis (Redict/Valkey) in coredis?

Feel free to close this if it's too off-topic -- I'm just curious what your thoughts are.

**Comment by alisaifee** [comment]
@coandco - completely open to it - I think the first step would be to add these to the CI compatibility matrix.

I have something like this for `keydb` & `dragonflydb` as well

**Comment by alisaifee** [comment]
Just added valkey to the CI and it mostly behaves as expected: https://github.com/alisaifee/coredis/actions/runs/8767165485/job/24060116715

**Comment by alisaifee** [comment]
Both redict and valkey are now tested against in the CI. Let me know if there's something else specific that you had in mind?

**Comment by coandco** [comment]
I think that's it.  Mostly it'll be good to know what the support level is if we end up moving to one of the open-source forks.
