### ISSUE TITLE
coredis installed from pip does not work

### ISSUE THREAD

**Issue by AxTheB** [alisaifee/coredis#23]
It looks like directory 'response' is missing from installation

## Checklist

- Python version
Python 3.9.7 (ubuntu impish package)

- Using hiredis or just Python parser

installed using `python -m pip install coredis[hiredis]`, as per info in readme

- Using uvloop or just asyncio event loop
asyncio

- Does issue exists against the `master` branch of aredis?

Yes

## Steps to reproduce
- create fresh venv `python3 -m venv testenv`
- acivate it `. ./testenv/bin/acivate`
- install coredis `python -m pip install coredis[hiredis]`
- copy and run example client from https://github.com/alisaifee/coredis#single-node-client

## Expected behavior
example code will do stuff with redis

## Actual behavior
 ```
Traceback (most recent call last):
  File "/home/ax/src/test/client.py", line 4, in <module>
    from coredis import Redis
  File "/home/ax/src/test/testenv/lib/python3.9/site-packages/coredis/__init__.py", line 9, in <module>
    from coredis.client import Redis, RedisCluster
  File "/home/ax/src/test/testenv/lib/python3.9/site-packages/coredis/client.py", line 25, in <module>
    from coredis.commands import ClusterCommandConfig, CommandGroup, redis_command
  File "/home/ax/src/test/testenv/lib/python3.9/site-packages/coredis/commands/__init__.py", line 30, in <module>
    from coredis.response.callbacks import ParametrizedCallback, SimpleCallback
ModuleNotFoundError: No module named 'coredis.response' 
```

- It is appreciated if error log can be provided

**Comment by alisaifee** [comment]
Thanks for the report (I really didn't expect anyone to pick it up that quick 😀) and catching that!
I've pushed a [3.0.1](https://coredis.readthedocs.io/en/latest/release_notes.html#v3-0-1) release that fixes that problem.
