### ISSUE TITLE
lmove can return None

### ISSUE THREAD

**Issue by jose-l-cerdeira-alb** [alisaifee/coredis#242]
lmove implementation should account for (nil) response from Redis.
it should return Optional[AnyStr] and the callback in self.execute_command should be OptionalAnyStrCallback[AnyStr]

There may be more commands in this situation like llen, but I've not checked

## Your Environment

- coredis version: 4.17.0
- Redis version: 7.0.15
- Operating system: debian 12
- Python version: 3.10

**Comment by alisaifee** [comment]
Thanks! If you could provide / update the tests with scenarios where this would be the return, they should actually fail since the tests use runtime typing and will fail on boundaries if the wrong type is returned.

**Comment by alisaifee** [comment]
Addressed in 8543614a088b3d40bb24fc18c39c4bc89ba0084d
