### ISSUE TITLE
Dead link in the documentation

### ISSUE THREAD

**Issue by coandco** [alisaifee/coredis#243]
On [the locking page](https://coredis.readthedocs.io/en/stable/recipes/locks.html) of the docs, a link has gone stale.  The phrase "[the distributed locking pattern described in redis docs](https://redis.io/docs/reference/patterns/distributed-locks/#correct-implementation-with-a-single-instance)" links to a bit-rotted link, and should instead link to https://redis.io/docs/latest/develop/use/patterns/distributed-locks/.

**Comment by alisaifee** [comment]
Thanks! Addressed in https://github.com/alisaifee/coredis/commit/b7be821e633d8a31e175e38e582a3f4d8b749196
