### ISSUE TITLE
Support python 3.13

### ISSUE THREAD

**Issue by hxyannay** [alisaifee/coredis#244]
Hey,
Would be very happy if you could support python 3.13 and create a new release and wheels compiled for python 3.12.
Thank you very much!

**Comment by hxyannay** [comment]
Hey @alisaifee, can you take a look?
Really looking forward to upgrading to python3.13 :)

**Comment by alisaifee** [comment]
Apologies for the delay in getting to this. I've added it to CI but unfortunately there's a few other unrelated issues in the build process that need to be ironed out before I can make a release.

**Comment by alisaifee** [comment]
Compiled wheels are available as of daad833a650126e92a166b3ffd07341f903c14e5. This is only in https://test.pypi.org/project/coredis/ at the moment but I'll make a release over the weekend.

**Comment by hxyannay** [comment]
Thanks @alisaifee :)
Could you cut a new release so those wheels will be available?
Thank you!

**Comment by alisaifee** [comment]
Apologies for the delay - the 4.18.0 release is now available with the compiled wheels.
