### ISSUE TITLE
Add support for a credential provider

### ISSUE THREAD

**Issue by trentbitterman** [alisaifee/coredis#246]
Currently, coredis allows authenticating with Redis clusters by supplying a username and password. This works in most situations, but in some cases, such as an [Elasticache cluster using IAM for auth](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/auth-iam.html), this can't be used as the "password" will rotate and there's no good way in coredis to update the password when it does. Other Redis libraries, [such as redis-py](https://redis-py.readthedocs.io/en/stable/examples/connection_examples.html#Connecting-to-a-redis-instance-with-ElastiCache-IAM-credential-provider.), allow the specification of a credential provider, which is basically just an object with a `get_credential` method that will return the current password when called. It would be useful if coredis had something similar.

## Expected Behaviour

In addition to supporting a [`password` string parameter](https://github.com/alisaifee/coredis/blob/3c2c72d0916b57c756e64cebf2398cfa1522a403/coredis/client/basic.py#L108), the various coredis clients should also allow passing in a credential provider object that coredis can use to query the password/credential whenever it is needed.

Thanks for all of your work on this library. It's really great!

**Comment by alisaifee** [comment]
Apologies for the late response. This makes a lot of sense and would be a pretty straightforward addition to the API. I'm open to a PR for this as I've had limited bandwidth recently for maintenance, however, if not - I'd appreciate any suggestions regarding which providers make sense as builtins versus just being documented as recipes or suggestions in the documentation.

**Comment by trentbitterman** [comment]
No worries. I'll work on putting something together and hopefully have a PR up sometime next week.

**Comment by alisaifee** [comment]
> No worries. I'll work on putting something together and hopefully have a PR up sometime next week.

Thank you! The state of master/CI is a lot more stable now (and python 3.13 compatible) so hopefully that should make things a little easier to work with.

**Comment by trentbitterman** [comment]
Great, thanks! I've put up a PR at #253 that I think should be ready for review. It looks like you'll need to trigger the gates for it. So far I only added a basic username and password provider and documented that plus the abstract class, so I can more if you think that would be better. Let me know what you'd prefer and if there are any changes you'd like to my PR. Thanks!

**Comment by alisaifee** [comment]
Great work, and I think the basic username/password support built in is fine (especially with the recipe for IAM being shipped with the package and well documented).

**Comment by alisaifee** [comment]
@trentbitterman: I made a few [changes](https://github.com/alisaifee/coredis/commits/master/coredis/recipes/credentials/iam_provider.py) to the IAM recipe. Specifically:
- use `aiobotocore` instead of `botocore`
- use `asyncache` to decorate the `get_credentials` method (the cachetools decorator was raising an error upon subsequent calls as it was returning an already awaiting coroutine)

Additionally I've added the dependencies needed for recipes in [requirements/recipes.txt](https://github.com/alisaifee/coredis/blob/master/requirements/recipes.txt) which can be used during installation by doing `pip install coredis[recipes]`.

I've done some basic testing to verify that this works functionally - but not much in terms of how this changes any performance characteristics. Perhaps you can take a look before I cut a release?

**Comment by trentbitterman** [comment]
Sure, I can take a look. Thanks for making those improvements!

**Comment by alisaifee** [comment]
Just FYI, I've cut the `4.18.0` release with the recipe using `aiobotocore`. If you find any issues or better approaches in your environment please do let me know since at the moment I have no real use case to test it out.

**Comment by trentbitterman** [comment]
Thanks. Sorry, I got busy with other things and haven't gotten around to testing it. I'll hopefully test it out later this week and let you know if I run into any issues.
