### ISSUE TITLE
Documentation: usefulness of hiredis?

### ISSUE THREAD

**Issue by AxTheB** [alisaifee/coredis#30]
Hello. The README states I can install coredis with optional dependency hiredis, but does not say why I would (or would not) want it.

**Comment by AxTheB** [comment]
Hm, found it, its there ([hiredis](https://pypi.org/project/hiredis) and [uvloop](https://pypi.org/project/uvloop) can make coredis faster, but it is up to you whether to install them or not.)

**Comment by alisaifee** [comment]
Sorry I missed this entirely. The documentation can definitely be better about the usefulness of both hiredis & uvloop. I'm going to reopen this and try to write up something in the docs/readme to clarify

**Comment by alisaifee** [comment]
Slightly  better than before I hope: 
- https://coredis.readthedocs.io/en/latest/#dependencies-supported-python-versions
- https://coredis.readthedocs.io/en/latest/api_reference.html#parsers

**Comment by AxTheB** [comment]
Thanks, that is very good explanation.
