### ISSUE TITLE
roadmap keyDB support

### ISSUE THREAD

**Issue by raphaelauv** [alisaifee/coredis#54]
Is there a roadmap for "full" keyDB support ?

Did you already list all the present and missing feature of this client ?

Could we contribute ? 

Thanks

**Comment by alisaifee** [comment]
Hi! I'm happy to take contributions/feature requests.
To clarify, what do you mean by "full" keyDB support? in terms of command coverage I only added the sub key expire commands. Are there others?

**Comment by raphaelauv** [comment]
some commands are not well documented -> https://github.com/Snapchat/KeyDB/blob/main/src/server.cpp

like hrename

**Comment by alisaifee** [comment]
Thanks for the details of the additional commands, they are indeed difficult to discover 😓 
I've put up a PR with the addition of the commands you mentioned (+ `PEXPIREMEMBERAT`).  Please have a look when you have a moment

**Comment by alisaifee** [comment]
master now has the additional keydb commands as referenced in this issue and #55. Additionally I've added a `KeyDBCluster` client which adds partial support for the extensions (`bitop lshift, rshift` and `cron` aren't routable in cluster simply).

**Comment by alisaifee** [comment]
[3.757](https://github.com/alisaifee/coredis/releases/tag/3.757) contains the additional commands for keydb
