### ISSUE TITLE
black in the ci missing `--check` ?

### ISSUE THREAD

**Issue by Le0Developer** [alisaifee/coredis#63]
https://github.com/alisaifee/coredis/blob/d0d5d78ae8e152273883b906f43c7e6b1c24ed42/.github/workflows/main.yml#L35

Working on #62, I ran `black .` and saw it affect ~10 files but the CI succeeded, so I suspect something is wrong with it.

**Comment by alisaifee** [comment]
Yeap, you're absolutely right.

**Comment by alisaifee** [comment]
Addressed in 71820979243cc729cd557c7133f2d42b0449331e
